CREATE
(SinnFein:Party{Name:"SinnFein"}),
(FiannaFail:Party{Name:"FiannaFail"}),
(FineGael:Party{Name:"FineGael"}),
(PeopleBeforeProfitAllianceAAA:Party{Name:"Anti-AusterityAlliance,PeopleBeforeProfitAlliance"}),
(Independent:Party{Name:"Independent"}),
(RenuaIreland:Party{Name:"RenuaIreland"}),
(SocialDemocrats:Party{Name:"SocialDemocrats"}),
(WorkersActionGroup:Party{Name:"Workers and unemployment action group"}),
(Greenparty:Party{Name:"Greenparty"}),
(IrishDemParty:Party{Name:"Irish Democratic Party"}),
(WorkersParty:Party{Name:"The Workers Party"}),
(DirectDemocracy:Party{Name:"Direct Democracy/National CitizensMovement"}),
(CPPC:Party{Name:"ThePeople'sConvention(CPPC)"}),
(CommunistParty:Party{Name:"CommunistPartyofIreland"}),
(FísNua:Party{Name:"FísNua"}),
(CatholicDems:Party{Name:"Catholic Democrats"});